- hosts: all
  gather_facts: false
  connection: local
  user: root

  vars_prompt:
    - name: "vcenter_hostname"
      prompt: "vcenter_hostname"
      private: no
      default: "vcsa"
    - name: vcenter_user
      prompt: "username"
      private: no
    - name: "vcenter_pass"
      prompt: "Password input"
      private: yes

  vars:
    datacenter: 'vmcluster'
    esxi_host: '192.168.2.108'
    notes: 'Created by Ansible'
    disk: 20
    test: secomvm100
    datastore: datastore1
    network: vmxnet3
    memory: 512
    cpu: 1
    osid: rhel6Guest

  tasks:
    - vsphere_guest:
        vcenter_hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        guest: "{{ test }}"
        state: present
        vm_extra_config:
          notes: "{{ notes }}"
        vm_disk:
          disk1:
            size_gb: "{{ disk }}"
            type: thin
            datastore: "{{ datastore }}"
        vm_nic:
          nic1:
            type: vmxnet3
            network: "{{ network }}"
            network_type: standard
        vm_hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ cpu }}"
          osid: "{{ osid }}"
          scsi: paravirtual
        esxi:
          datacenter: "{{ datacenter }}"
          hostname: "{{ esxi_host }}"
